spring.application.name=Monarch ERP

spring.profiles.active=local

spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp

spring.datasource.url=jdbc:postgresql://localhost:5432/monarch_erp
spring.datasource.username=postgres
spring.datasource.password=Tushar

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=false


jwt.secret=MonarchERPJwtSecretKeyThatIsAtLeast32CharsLong
jwt.access.expiration=3600000
jwt.refresh.expiration=604800000

monarch.sales.max-discount=15%

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

logging.level.org.springframework.security.web.FilterChainProxy=DEBUG


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MY_APP_MAIL_USER}
spring.mail.password=${MY_APP_MAIL_PASS}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.cache.type=redis
spring.cache.redis.time-to-live=60m
spring.cache.redis.cache-null-values=false
spring.cache.cache-names=product_page,products

# Force JSON as the default for all content negotiation
spring.mvc.contentnegotiation.default-content-type=application/json

# Ensure that even 404s follow this rule
server.error.whitelabel.enabled=false

spring.jackson.default-property-inclusion=non_null

logging.level.org.springframework.data.redis=DEBUG

# Kafka Connection
spring.kafka.bootstrap-servers=localhost:9092

# Producer Config
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# Consumer Config (So your monolith can also listen)
spring.kafka.consumer.group-id=monarch-erp-group
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*


