spring.application.name=Monarch ERP

spring.profiles.active=local

spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp

spring.datasource.url=jdbc:postgresql://localhost:5432/monarch_erp
spring.datasource.username=postgres
spring.datasource.password=Tushar

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true


jwt.secret=MonarchERPJwtSecretKeyThatIsAtLeast32CharsLong
jwt.access.expiration=3600000
jwt.refresh.expiration=604800000