spring.application.name=Monarch ERP
spring.profiles.active=local
spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/monarch_erp?reWriteBatchedInserts=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Tushar}
logging.level.org.hibernate.stat=DEBUG
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=false
jwt.secret=MonarchERPJwtSecretKeyThatIsAtLeast32CharsLong
jwt.access.expiration=3600000
jwt.refresh.expiration=604800000
monarch.sales.max-discount=15%
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MY_APP_MAIL_USER}
spring.mail.password=${MY_APP_MAIL_PASS}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.data.redis.host=${SPRING_REDIS_HOST:localhost}
spring.data.redis.port=6379
spring.cache.type=redis
spring.cache.redis.time-to-live=60m
spring.cache.redis.cache-null-values=false
spring.cache.cache-names=product_page,products
# Force JSON as the default for all content negotiation
spring.mvc.contentnegotiation.default-content-type=application/json
# Ensure that even 404s follow this rule
server.error.whitelabel.enabled=false
spring.jackson.default-property-inclusion=non_null
# Kafka Connection
spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.producer.batch-size=65536
spring.kafka.producer.properties.linger.ms=20
spring.kafka.producer.compression-type=snappy
# Producer Config
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
# Consumer Config (So your monolith can also listen)
spring.kafka.consumer.group-id=monarch-erp-group
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*
# Circuit Breaker Configuration
resilience4j.circuitbreaker.instances.variantServiceBreaker.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.variantServiceBreaker.slidingWindowSize=10
resilience4j.circuitbreaker.instances.variantServiceBreaker.minimumNumberOfCalls=10
resilience4j.circuitbreaker.instances.variantServiceBreaker.failureRateThreshold=50
resilience4j.circuitbreaker.instances.variantServiceBreaker.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.variantServiceBreaker.permittedNumberOfCallsInHalfOpenState=1
# Important: Enable Actuator endpoints so we can check the status

management.endpoint.health.show-details=always

# 1. Expose metrics for Prometheus/Grafana or Actuator
management.endpoints.web.exposure.include=health,info,metrics,prometheus,circuitbreakers
management.metrics.export.prometheus.enabled=true


spring.datasource.hikari.register-mbeans=true
spring.datasource.hikari.leak-detection-threshold=2000
spring.datasource.hikari.maximum-pool-size=5

cloudinary.cloud-name=dpc0fzee9
cloudinary.api-key=967363278818812
cloudinary.api-secret=3pyJHv-lXwx55vj7QJ9S3fKGfiQ


spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB



spring.jpa.properties.hibernate.jdbc.batch_size=50
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
spring.jpa.properties.hibernate.jdbc.batch_versioned_data=true

# Stop Kafka logs (connection, polling, heartbeat)
logging.level.org.apache.kafka=ERROR
logging.level.org.springframework.kafka=ERROR

# Stop Redis/Lettuce/Jedis logs
logging.level.org.springframework.data.redis=ERROR
logging.level.io.lettuce.core=ERROR

# Stop Resilience4j (Circuit Breaker) logs
logging.level.io.github.resilience4j=ERROR

# Stop General Spring Framework noise
logging.level.org.springframework=WARN
logging.level.org.springframework.web=WARN

# Stop Cloudinary and Multipart logs
logging.level.com.cloudinary=ERROR
logging.level.org.springframework.web.multipart=ERROR

# 1. Enable statistics to see the batch summary
spring.jpa.properties.hibernate.generate_statistics=true

# 2. Log JDBC details (This is the "Smoking Gun")
logging.level.org.hibernate.engine.jdbc.batch.internal.BatchingBatch=TRACE


# This is required to actually print the summary table in the console
logging.level.org.hibernate.engine.internal.StatisticalLoggingSessionEventListener=INFO
logging.level.org.hibernate.orm.jdbc.batch=TRACE
logging.level.org.hibernate.orm.jdbc.bind=TRACE
logging.level.org.hibernate.engine.jdbc.batch=TRACE


